-- Hand-edited for idempotency: CREATE TYPE wrapped in duplicate_object guards
-- so the migration is safe to re-run. Tables/FKs/indexes already use
-- IF NOT EXISTS / duplicate_object. Generated by drizzle-kit, then guarded.
DO $$ BEGIN
 CREATE TYPE "public"."auspicious_band" AS ENUM('NONE', 'LOW', 'MEDIUM', 'HIGH', 'PEAK');
EXCEPTION WHEN duplicate_object THEN null;
END $$;--> statement-breakpoint
DO $$ BEGIN
 CREATE TYPE "public"."b2b_account_status" AS ENUM('PENDING', 'VERIFIED', 'REJECTED', 'SUSPENDED');
EXCEPTION WHEN duplicate_object THEN null;
END $$;--> statement-breakpoint
DO $$ BEGIN
 CREATE TYPE "public"."calendar_event_kind" AS ENUM('MUHURAT', 'FESTIVAL', 'SCHOOL', 'GOVT', 'REGIONAL', 'BLACKOUT');
EXCEPTION WHEN duplicate_object THEN null;
END $$;--> statement-breakpoint
DO $$ BEGIN
 CREATE TYPE "public"."capacity_status" AS ENUM('OPEN', 'HELD', 'BOOKED', 'BLOCKED');
EXCEPTION WHEN duplicate_object THEN null;
END $$;--> statement-breakpoint
DO $$ BEGIN
 CREATE TYPE "public"."contract_status" AS ENUM('DRAFT', 'SENT', 'SIGNED', 'VOID');
EXCEPTION WHEN duplicate_object THEN null;
END $$;--> statement-breakpoint
DO $$ BEGIN
 CREATE TYPE "public"."esign_provider" AS ENUM('DIGILOCKER', 'SIGNZY');
EXCEPTION WHEN duplicate_object THEN null;
END $$;--> statement-breakpoint
DO $$ BEGIN
 CREATE TYPE "public"."money_currency" AS ENUM('INR', 'USD', 'GBP', 'EUR', 'AED', 'CAD', 'AUD', 'SGD');
EXCEPTION WHEN duplicate_object THEN null;
END $$;--> statement-breakpoint
DO $$ BEGIN
 CREATE TYPE "public"."pricing_rule_status" AS ENUM('ACTIVE', 'INACTIVE');
EXCEPTION WHEN duplicate_object THEN null;
END $$;--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "b2b_accounts" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"profile_id" uuid NOT NULL,
	"legal_name" varchar(255) NOT NULL,
	"gstin" varchar(15) NOT NULL,
	"hsn_sac" varchar(20),
	"billing_address" text,
	"contact_email" varchar(255),
	"contact_phone" varchar(20),
	"status" "b2b_account_status" DEFAULT 'PENDING' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "calendar_events" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"kind" "calendar_event_kind" NOT NULL,
	"name" varchar(255) NOT NULL,
	"event_date" date NOT NULL,
	"end_date" date,
	"region" varchar(100),
	"source" varchar(100) NOT NULL,
	"auspicious_band" "auspicious_band" DEFAULT 'NONE' NOT NULL,
	"metadata" jsonb,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "contracts" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"profile_id" uuid NOT NULL,
	"template_id" varchar(100) NOT NULL,
	"title" varchar(255) NOT NULL,
	"status" "contract_status" DEFAULT 'DRAFT' NOT NULL,
	"provider" "esign_provider",
	"signed_asset_key" varchar(500),
	"content_hash" varchar(64),
	"sent_at" timestamp,
	"signed_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "pricing_rules" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"profile_id" uuid NOT NULL,
	"service_category" varchar(100) NOT NULL,
	"base_paise" bigint NOT NULL,
	"currency" "money_currency" DEFAULT 'INR' NOT NULL,
	"floor_multiplier" double precision DEFAULT 1 NOT NULL,
	"ceiling_multiplier" double precision DEFAULT 1 NOT NULL,
	"muhurat_multiplier" double precision DEFAULT 1 NOT NULL,
	"off_season_multiplier" double precision DEFAULT 1 NOT NULL,
	"demand_multiplier" double precision DEFAULT 1 NOT NULL,
	"status" "pricing_rule_status" DEFAULT 'ACTIVE' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "vendor_capacity" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"profile_id" uuid NOT NULL,
	"start_at" timestamp NOT NULL,
	"end_at" timestamp NOT NULL,
	"status" "capacity_status" DEFAULT 'OPEN' NOT NULL,
	"max_bookings" integer DEFAULT 1 NOT NULL,
	"booked_count" integer DEFAULT 0 NOT NULL,
	"off_season" boolean DEFAULT false NOT NULL,
	"notes" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "b2b_accounts" ADD CONSTRAINT "b2b_accounts_profile_id_profiles_id_fk" FOREIGN KEY ("profile_id") REFERENCES "public"."profiles"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "contracts" ADD CONSTRAINT "contracts_profile_id_profiles_id_fk" FOREIGN KEY ("profile_id") REFERENCES "public"."profiles"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "pricing_rules" ADD CONSTRAINT "pricing_rules_profile_id_profiles_id_fk" FOREIGN KEY ("profile_id") REFERENCES "public"."profiles"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "vendor_capacity" ADD CONSTRAINT "vendor_capacity_profile_id_profiles_id_fk" FOREIGN KEY ("profile_id") REFERENCES "public"."profiles"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "b2b_accounts_profile_status_idx" ON "b2b_accounts" USING btree ("profile_id","status");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "b2b_accounts_gstin_uniq" ON "b2b_accounts" USING btree ("gstin");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "calendar_events_kind_date_idx" ON "calendar_events" USING btree ("kind","event_date");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "calendar_events_date_idx" ON "calendar_events" USING btree ("event_date");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "contracts_profile_status_idx" ON "contracts" USING btree ("profile_id","status","created_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "pricing_rules_profile_status_idx" ON "pricing_rules" USING btree ("profile_id","status","created_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "vendor_capacity_profile_status_idx" ON "vendor_capacity" USING btree ("profile_id","status","created_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "vendor_capacity_window_idx" ON "vendor_capacity" USING btree ("start_at","end_at");